[WIP] Spike: adding test on http level for platform-api
dolittle/platform-api pull request #123
Opened 2022-05-05 21:51 UTC by goeran

Http is a nice abstraction to add tests to.

2022-08-01 09:44 UTC, joelhoisko requested changes
Nice work, lots of changes to go through:

- How did you actually update this? Me and Jakob have both struggled with this in the past due to the `json-iter` package panicking or something and would be nice to know the fix. What were the commands that you ran to update the project?
- Have you tested this locally or against production? Have you tested that the docker images build and run correctly?

Nice to see you getting to code in the platform-api and with tests too 👍

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/k8s/foobar.go
> +type K8sPlatformRepo interface {
My reasoning for moving it is because usually in go I would like to declare the interfaces by their consumers. So if there was a struct that would consume `K8sRepo` I would like that struct to be the one declaring the functions that it wants and then it's up to the interfaces implementor to implement those. So instead of "I'm an interface, these are my methods for you to consume" it's more of a "I'm an interface, I define the things that I need from somebody".

But in the case of `K8sRepo` there isn't a single consumer, so maybe the approach then is to keep the interface in it's own file. This interface doesn't really follow the idea of interfaces in go so...

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/k8s/k8s_repo.go
> +	fmt.Println("Tryprtint")
```suggestion
```

Leftovers

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/k8s/k8s_repo.go
> +	fmt.Println("Foobarx")
```suggestion
```

Leftovers

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/microservice/doc.go
> +package microservice
I assume this file was created by accident and it can be deleted maybe?

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/microservice/rawdatalog/nats.go
> +								ProbeHandler: corev1.ProbeHandler{
I assume these changes are from updating the dependencies and I'm assuming that they still work. Not like we use this part of the code anyway so.

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/storage/git/git_storage.go
> +
```suggestion
```

Leftovers

2022-08-01 09:44 UTC, joelhoisko commented on pkg/platform/storage/git/git_storage.go
> +}
Is there a reason not to just use `s.Directory`? Or if we want to keep the `Directory` property private then we should also make it private (lowercase it), otherwise this encapsulation doesn't really do anything. Or did you have something in mind for tests down the line?

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/server_test.go
> +		It("should rertun 403 Forbidden when x-shared-secret header is invalid", func() {
```suggestion
		It("should return 403 Forbidden when x-shared-secret header is invalid", func() {
```

typo

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/server_test.go
> +		It("should rertun 403 Forbidden when x-shared-secret header is invalid", func() {
```suggestion
		It("should return 403 Forbidden when x-shared-secret header is invalid", func() {
```

typo

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/mocks/k8splatformrepo_mock.go
> +package mocks
You don't have to write the mocks yourself, if you have interfaces defined then you can just run `make build-mocks` to build them using `mockery`. Then you can use those mocks with the proper `testify` library that has all the stuff around stubbing, mocking calls, asserting they worked etc etc. You do have to install mockery on your computer manually sadly.

Or was there maybe something blocking you from using mockery? I can now see that this testing was probably the reason why you put the git code inside the `storage.Repo` interface so that you could get it to work.

Example on how to use the mocks (there's many other places too to check them):
https://github.com/dolittle/platform-api/blob/3ca8a74fc6df4810dc9547416ada48a71998fdbe/pkg/platform/microservice/m3connector/m3connector_test.go#L185-L225

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/git-test.go
> +		dir := filepath.Join(gitRepo.GetDirectory(), "dev", "453e04a7-4f9d-42f2-b36c-d51fa2c83fa3")
Same stuff here about the encapsulation of the `Directory` property as I talked in the comment around `gitRepo`

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/server_test.go
> +		logContext := logrus.StandardLogger()
```suggestion
		logContext, _ = logrusTest.NewNullLogger()
```

You can also use the null logger from this package (the returned type from `NewNullLogger()` might be wrong but you get the idea):
```go
	logrusTest "github.com/sirupsen/logrus/hooks/test"
```

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/server_test.go
> +		}})
This setup could be moved inside the `Describe("When fetch images from Container Registry")` block, as it's specific to that testing. Same goes for the paths I think, just to keep things together.

2022-08-01 09:44 UTC, joelhoisko commented on cmd/api/server.go
> +		"/application/{applicationID}/containerregistry/tags2/{imageName:.*}",
Same thing here about the `tags2` naming. And shouldn't it be a `repoName` or something like that that is passed in here? Or maybe I have misunderstood the whole thing.

2022-08-01 13:22 UTC, eliasgs commented on pkg/platform/containerregistry/azurerepo.go
> +func (repo azureRepo) GetTags2(credentials ContainerRegistryCredentials, image string) ([]ImageTag, error) {
I changed this to GetImageTags

2022-08-01 13:23 UTC, eliasgs commented on pkg/platform/containerregistry/service.go
> +}
Changed to HTTPResponseImageTags

2022-08-01 13:30 UTC, eliasgs commented on pkg/platform/microservice/rawdatalog/nats.go
> +								ProbeHandler: corev1.ProbeHandler{
Yes, they have renamed some stuff. I'm assuming they still work as well - not sure how test this?

2022-08-01 13:35 UTC, eliasgs commented on cmd/api/server.go
> +		"/application/{applicationID}/containerregistry/tags2/{imageName:.*}",
We get tags by image name, so this should be fine.

2022-08-02 09:11 UTC, joelhoisko commented on pkg/platform/microservice/rawdatalog/nats.go
> +								ProbeHandler: corev1.ProbeHandler{
Tbh I wouldn't worry too much about it, not even sure if they have worked for a while.

2022-08-18 08:13 UTC, joelhoisko approved these changes
:shipit:

2022-08-18 08:15 UTC, merged