Command to copy env variables for a microservice from en env to a new env
dolittle/platform-api pull request #141
Opened 2022-06-16 10:19 UTC by goeran

## Summary
This was implemented to speed up Platform Engineers time spent on copying microservices from an environment to a new environment. 

With this command it's possible to copy env vars for a microservice in a specific environment to a new environment.

2022-06-16 12:16 UTC, joelhoisko requested changes
Nice, here are my thoughts:

To make the commands semantics a bit more aligned with the other commands and their design I think there are 2 main options:
- Create a new structure and folders along the lines of `tools microservice copy environment`. This is because this command doesn't have anything to do with Studio really, the other commands inside the `studio` parent command deal with more Studio specific stuff like upserting the different json files that platform-api serves to Studio. Granted it's not always that clear cut, but in this case this command sounds like it does something to the `studio.json` file or the actual Studio deployments. What this command ultimately deals with to me sounds more like microservices, eg "copy this microservices environment variables from this environment to this environment". Maybe it could also have something to do with environments, but that might be a bit of a reach. So I propose:
  - New folder and subcommand `microservice` inside `tools`. In the future we can start placing other microservice specific commands in here
  - New folder and subcommand/verb `copy` inside `microservice`. Similar setup as we have with the `tools studio` command where we have different verbs that act in Studios "domain".
  - The actual command `environment`/`env`/`env-variables`/`environment-variables`, indicating that this command acts on the microservices environment variables. So a full command could look something like `tools microservice copy env`
- If the above is a bit too much work for now (this is a "one off" like command after all), I'd suggest to just create a new verb `copy` inside the `studio` subcommand and then have the `environment`/`env`/`env-variables`/`environment-variables` be the actual commands name. So it would look like `tools studio copy env --microservice-name --from-env --to-env`. 


Overall another point would be to try to add this copy thing into some type of abstraction in platform-api to be used later by some other pieces of the code, but that could happen later (and tests etc)

2022-06-16 12:16 UTC, joelhoisko commented on cmd/tools/studio/cfg/copyenv.go
> +var heyCMD = &cobra.Command{
```suggestion
var copyenvCMD = &cobra.Command{
```

I assume heyCMD wasn't planned on being the final name :D

2022-06-16 12:16 UTC, joelhoisko commented on cmd/tools/studio/cfg/copyenv.go
> +		}).Info("Begins to copy env var configmap")
```suggestion
		logContext = logContext.WithFields(logrus.Fields{
			"k8sNamespace":     namespace,
			"k8sConfigmap":     sourceConfigMapName,
			"microserviceName": sourceMicroserviceName,
		})
		logContext.Info("Begins to copy env var configmap")
```

This way you save the properties that are setup into the `logContext` for later use.

2022-06-16 12:16 UTC, joelhoisko commented on cmd/tools/studio/cfg/copyenv.go
> +		}
```suggestion
		ctx := context.TODO()
		k8sClient, _ := platformK8s.InitKubernetesClient()
		configMap, err := k8sClient.CoreV1().ConfigMaps(namespace).Get(ctx, sourceConfigMapName, metav1.GetOptions{})
		if err != nil {
			logContext.Fatal(err)
		}
```

Suggestion code not exact and missing imports, but should give you the idea.

Instead of just using raw `exec` powers, I suggest to use the k8s go SDK instead. If this command stays inside the `studio` subcommand then it already has the flags setup for kubeconfig, then you only need to call initialize the k8s client in the command and start using it.
https://github.com/dolittle/platform-api/blob/f643513e96152fdaf0675542258cbfc914114c88/cmd/tools/studio/root.go#L35-L41

2022-06-16 12:16 UTC, joelhoisko commented on cmd/tools/studio/cfg/copyenv.go
> +		}).Info("Successfully copied configmap for env variables")
```suggestion
		logContext.Info("Successfully copied configmap for env variables")
```

If you setup the properties earlier then you don't need to keep repeating them.

2022-06-16 12:16 UTC, joelhoisko commented on cmd/tools/studio/cfg/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", heyCMD.PersistentFlags().Lookup("to-env"))
You don't need to use the `PersistentFlags()`, you can just use `Flags()`, that way these flags don't become global to any subcommands

2022-06-16 18:46 UTC, goeran commented on cmd/tools/studio/cfg/copyenv.go
> +var heyCMD = &cobra.Command{
Lol :) no. Renamed

2022-06-16 18:47 UTC, goeran commented on cmd/tools/studio/cfg/copyenv.go
> +		}).Info("Successfully copied configmap for env variables")
You are correct. I'll fix

2022-06-16 18:47 UTC, goeran commented on cmd/tools/studio/cfg/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", heyCMD.PersistentFlags().Lookup("to-env"))
Thanks for the input. Will fix

2022-06-16 18:54 UTC, goeran commented on cmd/tools/studio/cfg/copyenv.go
> +		}).Info("Begins to copy env var configmap")
Done

2022-06-16 19:13 UTC, goeran commented on cmd/tools/studio/cfg/copyenv.go
> +		}
@joelhoisko  I think this is a good idea, but I don't think I want to spend more time on it. I think we can write this off as tech debt. When we incorporate copy of env variables into the platform-api we can rewrite it. Make sense?

2022-06-17 11:37 UTC, joelhoisko requested changes

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", environmentCMD.Flags().Lookup("to-env"))
```suggestion
	environmentCMD.Flags().String("application", "", "application id")
	environmentCMD.MarkFlagRequired("application")
	viper.BindPFlag("tools.microservice.copy.environment.application", environmentCMD.Flags().Lookup("application"))

	environmentCMD.Flags().String("microservice-name", "", "Name of microservice to copy environment variables from")
	environmentCMD.MarkFlagRequired("microservice-name")
	viper.BindPFlag("tools.microservice.copy.environment.microservice-name", environmentCMD.Flags().Lookup("microservice-name"))

	environmentCMD.Flags().String("from-env", "", "The environment to copy from")
	environmentCMD.MarkFlagRequired("from-env")
	viper.BindPFlag("tools.microservice.copy.environment.from-env", environmentCMD.Flags().Lookup("from-env"))

	environmentCMD.Flags().String("to-env", "", "they environment to copy to")
	environmentCMD.MarkFlagRequired("to-env")
	viper.BindPFlag("tools.microservice.copy.environment.to-env", environmentCMD.Flags().Lookup("to-env"))
```

The flags aren't persistent anymore so we can just use `MarkFlagRequired()`. These flags are also set on the `environmentCMD` only, so these flag/viper setups should be moved to the `environment.go` file's `init()` function so that they are self contained.

I also think that the viper strings should be changed to match the command, so `tools.microservice.copy.environment` etc. This is a minor thing because our viper configuration thing is all over the place anyways and in this case it's not even needed, you could do with just the `cobra` commands flags etc.

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/environment.go
> +	},
```suggestion
		destinationConfigMap := fmt.Sprintf("%s-%s-env-variables", destinationEnvironment, sourceMicroserviceName)
		logContextWithMeta := logContext.WithFields(logrus.Fields{
			"k8sNamespace": namespace,
			"k8sConfigmap": sourceConfigMapName,
			"k8sDestinationConfigMap": destinationConfigMap,
			"microserviceName": sourceMicroserviceName,
		})

		logContextWithMeta.Info("Begins to copy env var configmap")

		kubeCtlGetCfgMap := exec.Command("kubectl", "-n", namespace, "get", "configmap", sourceConfigMapName, "-o", "json")
		_, err := kubeCtlGetCfgMap.StderrPipe()
		if err != nil {
			logContext.Fatal(err)
			return
		}

		configMapJson, err := kubeCtlGetCfgMap.Output()
		if err != nil {
			logContextWithMeta.WithField("error", err).
				Fatal("Failed to get configmap")
			return
		}

		var modifiedConfigMap map[string]interface{}
		json.Unmarshal(configMapJson, &modifiedConfigMap)
		metadata := modifiedConfigMap["metadata"].(map[string]interface{})
		metadata["name"] = destinationConfigMap
		// delete uid and version to ensure it patches
		delete(metadata, "resourceVersion")
		delete(metadata, "uid")
		out, _ := json.Marshal(modifiedConfigMap)

		kubectlApply := exec.Command("kubectl", "-o", "json", "apply", "-f", "-")
		kubectlApply.Stdin = bytes.NewReader(out)
		kubectlApply.Stderr = os.Stderr

		kubectlApply.Start()
		kubeCtlGetCfgMap.Run()
		kubectlApply.Wait()

		logContextWithMeta.Info("Successfully copied configmap for env variables")
	},
```

It makes the logging easier if you just setup all the properties from the start, that way you don't have to keep adding the fields temporarily later to a single log line.

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/environment.go
> +	`,
```suggestion
	go run main.go tools microservice copy environment --application cde2e951-d40a-3548-8b45-64c0ded97940 \
		--microservice-name frontend \
		--from-env test \
		--to-env prod
	`,
```

Just fixing the old doc string

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/environment.go
> +	},
```suggestion
		destinationConfigMap := fmt.Sprintf("%s-%s-env-variables", destinationEnvironment, sourceMicroserviceName)
		logContextWithMeta := logContext.WithFields(logrus.Fields{
			"k8sNamespace": namespace,
			"k8sConfigmap": sourceConfigMapName,
			"k8sDestinationConfigMap": destinationConfigMap,
			"microserviceName": sourceMicroserviceName,
		})

		logContextWithMeta.Info("Begins to copy env var configmap")

		kubeCtlGetCfgMap := exec.Command("kubectl", "-n", namespace, "get", "configmap", sourceConfigMapName, "-o", "json")
		_, err := kubeCtlGetCfgMap.StderrPipe()
		if err != nil {
			logContext.Fatal(err)
			return
		}

		configMapJson, err := kubeCtlGetCfgMap.Output()
		if err != nil {
			logContextWithMeta.WithField("error", err).
				Fatal("Failed to get configmap")
			return
		}

		var modifiedConfigMap map[string]interface{}
		json.Unmarshal(configMapJson, &modifiedConfigMap)
		metadata := modifiedConfigMap["metadata"].(map[string]interface{})
		metadata["name"] = destinationConfigMap
		// delete uid and version to ensure it patches
		delete(metadata, "resourceVersion")
		delete(metadata, "uid")
		out, _ := json.Marshal(modifiedConfigMap)

		kubectlApply := exec.Command("kubectl", "-o", "json", "apply", "-f", "-")
		kubectlApply.Stdin = bytes.NewReader(out)
		kubectlApply.Stderr = os.Stderr

		kubectlApply.Start()
		kubeCtlGetCfgMap.Run()
		kubectlApply.Wait()

		logContextWithMeta.Info("Successfully copied configmap for env variables")
	},
```

It makes the logging easier if you just setup all the properties from the start, that way you don't have to keep adding the fields temporarily later to a single log line.

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/environment.go
> +	},
```suggestion
		destinationConfigMap := fmt.Sprintf("%s-%s-env-variables", destinationEnvironment, sourceMicroserviceName)
		logContextWithMeta := logContext.WithFields(logrus.Fields{
			"k8sNamespace": namespace,
			"k8sConfigmap": sourceConfigMapName,
			"k8sDestinationConfigMap": destinationConfigMap,
			"microserviceName": sourceMicroserviceName,
		})

		logContextWithMeta.Info("Begins to copy env var configmap")

		kubeCtlGetCfgMap := exec.Command("kubectl", "-n", namespace, "get", "configmap", sourceConfigMapName, "-o", "json")
		_, err := kubeCtlGetCfgMap.StderrPipe()
		if err != nil {
			logContext.Fatal(err)
			return
		}

		configMapJson, err := kubeCtlGetCfgMap.Output()
		if err != nil {
			logContextWithMeta.WithField("error", err).
				Fatal("Failed to get configmap")
			return
		}

		var modifiedConfigMap map[string]interface{}
		json.Unmarshal(configMapJson, &modifiedConfigMap)
		metadata := modifiedConfigMap["metadata"].(map[string]interface{})
		metadata["name"] = destinationConfigMap
		// delete uid and version to ensure it patches
		delete(metadata, "resourceVersion")
		delete(metadata, "uid")
		out, _ := json.Marshal(modifiedConfigMap)

		kubectlApply := exec.Command("kubectl", "-o", "json", "apply", "-f", "-")
		kubectlApply.Stdin = bytes.NewReader(out)
		kubectlApply.Stderr = os.Stderr

		kubectlApply.Start()
		kubeCtlGetCfgMap.Run()
		kubectlApply.Wait()

		logContextWithMeta.Info("Successfully copied configmap for env variables")
	},
```

It makes the logging easier if you just setup all the properties from the start, that way you don't have to keep adding the fields temporarily later to a single log line.

2022-06-17 11:37 UTC, joelhoisko commented on cmd/tools/microservice/copy/environment.go
> +	},
Not sure what the hell GitHub is reporting here as all these suggestions, but you get the point.

2022-06-17 18:04 UTC, goeran commented on cmd/tools/microservice/copy/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", environmentCMD.Flags().Lookup("to-env"))
@joelhoisko thanks. I will fix.

2022-06-17 18:04 UTC, goeran commented on cmd/tools/microservice/copy/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", environmentCMD.Flags().Lookup("to-env"))
Agree with both of your suggestions.

2022-06-17 18:05 UTC, goeran commented on cmd/tools/microservice/copy/environment.go
> +	`,
Agreed!

2022-06-17 18:05 UTC, goeran commented on cmd/tools/microservice/copy/environment.go
> +	},
I think you emphasised it well 😆 I'm on it

2022-06-17 18:27 UTC, goeran commented on cmd/tools/microservice/copy/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", environmentCMD.Flags().Lookup("to-env"))
Now using MarkFlagRequired.

2022-06-17 18:33 UTC, goeran commented on cmd/tools/microservice/copy/root.go
> +	viper.BindPFlag("tools.studio.cfg.to-env", environmentCMD.Flags().Lookup("to-env"))
keys for viper also fixed.

2022-06-17 18:34 UTC, goeran commented on cmd/tools/microservice/copy/environment.go
> +	},
I agree, but it's not always the same fields.

2022-06-17 18:34 UTC, goeran commented on cmd/tools/microservice/copy/environment.go
> +	`,
Fixed.

2022-06-17 18:51 UTC, merged