Use configured tenant when creating POAPI and RawDataLogIngestor
dolittle/platform-api pull request #22
Opened 2021-09-14 21:25 UTC by woksin

## Summary

When creating Purchase Order API microservice or RawDataLogIngestor microservice it is important to configure it to the correct tenant. The tenant being used before was just a static tenant, it needs to not be static in order for it to work with actual customers.

There are a few caveats at the moment:
- It will only use one tenant. For instance if we needed a Purchase Order API to commit events to multiple tenants that wouldn't work with the current solution
- The added configured tenant is not used for the other microservices yet. Only used for Purchase Order API and RawDataLogIngestor
- When we want to do this for normal microservices we need to change this to configure for all tenants, not just the first one 

### Added

- A method for getting tenant for environment on the application metadata stored in git
- Specs for method for getting tenant for environment on the application metadata stored in git 

### Changed

- The tenant used when creating Purchase Order API and RawDataLogIngestor
- A couple of places in the code 'tenant' parameter was renamed to 'customer' to make it more explicit that the tenant actually represents a Dolittle customer

2021-09-14 21:32 UTC, woksin commented
I was a little unsure on how I wanted to implement the functionality for getting the configured tenant. I know I wanted to write specs for it so the options I had in mind was to:
- Add methods to the stored application struct (as I did)
- Add functions that take in the stored application struct as a parameter

I'm open to suggestions if there are better ways of doing this

2021-09-15 08:07 UTC, joelhoisko requested changes
Bueno stuff, one real suggestion/point and one point about how the `resources.json` in the platform are a bit messy.

2021-09-15 08:07 UTC, joelhoisko commented on pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory.go
> +	readmodelDBName := resources[tenantID].Readmodels.Database
Not all `resources.json` files have the `readModels` key, it's a semi-legacy thing from the past and it mostly exists because usually the head code also reads the same `resources.json`, but that is just a convention and not enforced by anything really. But this is also touching upon the fact that not all customers applications have a read model store. The closest "official" thing would be our projection/embedding store resource definitions. We could also just get the `mongoDBURL` from the event store definition and then create the `readmodelDBName` from something.

For now this'll do, but we have to think of something in the future.

2021-09-15 08:07 UTC, joelhoisko commented on pkg/platform/microservice/service.go
>  				"Tenant %s with application %s in environment %s does not allow changes via Studio",
```suggestion
				"Customer %s with application %s in environment %s does not allow changes via Studio",
```

Should we also change it to "Customer" in here? We've really muddied the waters with different types of tenants 😂

2021-09-15 08:28 UTC, woksin commented on pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory.go
> +	readmodelDBName := resources[tenantID].Readmodels.Database
Yeah, it has been like that so I did not want to touch it.

2021-09-15 10:12 UTC, jakhog commented on pkg/platform/microservice/service.go
>  				"Tenant %s with application %s in environment %s does not allow changes via Studio",
I vote for gradually changing the "tenants of dolittle" -> "customers". As Joel said, it's a bit tricky to always have to specify which kind of tenant we're talking about in conversations and in the code. I think it would be too big of a job to fix all references right away, but changing as we come across it is fine by me.

2021-09-15 10:55 UTC, woksin commented on pkg/platform/microservice/service.go
>  				"Tenant %s with application %s in environment %s does not allow changes via Studio",
I agree.  Then I'll commit the suggestion

2021-09-15 11:00 UTC, joelhoisko approved these changes

2021-09-15 11:00 UTC, merged