Not json + first need to lookup service account
dolittle/platform-api pull request #52
Opened 2021-11-05 12:04 UTC by freshteapot

## Summary
- Specific endpoint for azure-devops to not expose all service accounts.
- Lookup service account to find the secret name.

2021-11-05 12:05 UTC, freshteapot commented
Follow up from #50.

2021-11-09 09:24 UTC, joelhoisko requested changes

2021-11-09 09:24 UTC, joelhoisko commented on pkg/platform/cicd/service.go
> +	vars["name"] = "azure-devops"
Currently the only reason why we use the words "Azure" in here is because we decided to when we created the service account to name it like that. But in the future this service account would be used for all sorts of other CI/CD pipelines, scripts etc. There is nothing specific to Azure Devops about the service account.

So maybe having something more generic would be nice, maybe just a simple "devops" (as loaded of a term as it is, I don't really like it but you get the idea). This would also mean that we'd have to rename the service account in operations and break somebodys workflow again so it might not be the best right now so I understand if we just wanna get this done now. But in the future I would much prefer that this service account would be more generic, or that the user can create specific service accounts with specific permissions for their different CI/CD needs (which is a lot more work).

2021-11-09 10:34 UTC, joelhoisko approved these changes

2021-11-09 10:35 UTC, merged