WIP: Public url for microservices in the platform but not in studio
dolittle/platform-api pull request #65
Opened 2021-11-29 16:30 UTC by freshteapot

## Summary

- Renaming a horrible name + wondering how to bubble up ingress from mi…

2021-11-30 11:00 UTC, freshteapot commented
# Info
- Linked to https://github.com/dolittle/Studio/pull/139

2021-11-30 14:38 UTC, joelhoisko requested changes
Nice work and tests too :) One question about comparing structs though.

2021-11-30 14:38 UTC, joelhoisko commented on pkg/platform/k8s_repo.go
> +				})
This led me down the rabbit hole on how to compare structs in golang and I found that structs are comparable with the basic [`==` equality operator](https://www.geeksforgeeks.org/structure-equality-in-golang/). So is there a reason you're going the way of JSONifying the structs first? Like relying on some of the structs JSON annotations to clean up the strings?

2021-12-01 10:07 UTC, freshteapot commented on pkg/platform/k8s_repo.go
> +				})
I can't explain it, with proof. So we shall use the "==", its cleaner :).
If I ever stumble upon the reason why, I will come back to you. But for now, I am keen to embrace this as its cleaner.

I thought there was something about pointers, but the documentation tells me I am wrong and running the code in question with some printing confirmed, whatever I am trying to sell, does not apply here :P.

```go
for _, rule := range ingress.Spec.Rules {
	for _, rulePath := range rule.HTTP.Paths {
		// For now, there is no need to expose it
		rulePath.Backend = networkingv1.IngressBackend{}

		diffA, _ := json.Marshal(rulePath)
		fmt.Println("HELLO", len(items))
		items = append(items, rulePath)
		exists := funk.Contains(items, func(item networkingv1.HTTPIngressPath) bool {
			diffB, _ := json.Marshal(item)
			fmt.Println("operator match", rulePath == item)
			fmt.Println("string match", string(diffA) == string(diffB))
			return string(diffA) == string(diffB)
		})

		if exists {
			continue
		}
		items = append(items, rulePath)
	}
}
```

2021-12-01 12:23 UTC, joelhoisko approved these changes

2021-12-01 13:36 UTC, merged