Add pull-dolittle-config command
dolittle/platform-api pull request #73
Opened 2022-01-19 13:16 UTC by joelhoisko

## Summary

Adds new command `pull-dolittle-config` which pulls all of the `*-dolittle` configmaps from the cluster and writes them into the `Source/V3/Kubernetes/Customers/<customer>/<application>/<environment>/<microservice>/microservice-configmap.dolittle.yml` files. 

Usage:
```sh
go run main.go tools pull-dolittle-config <repo-root>
```

2022-01-19 13:18 UTC, joelhoisko commented
We should also discuss if the `managedFields` should be removed from the output.

2022-01-21 10:00 UTC, freshteapot requested changes
Almost there :)

2022-01-21 10:00 UTC, freshteapot commented on pkg/platform/automate/share.go
> +		// TODO this is a sign it might not be using a runtime, maybe we skip
Should we warn?
I cant decide if we should return an error here.
Perhaps later, when we do know the microservice kind, we can add logic to handle if it should do what it currently does, or return an error.

Ie simple == includes runtime and should error

Hmm I just realised, we can have "simple" and not use the runtime.... we might have to return to this.

2022-01-24 10:18 UTC, joelhoisko commented on cmd/tools/automate/update-dolittle-config.go
> +					// TODO this might be to strict, perhaps we have a flag to let them skip?
Looking at the code the only way the `automate.GetDolittleConfigMaps()` is going to error is if the underlying `client.CoreV1().ConfigMaps(namespace).List()` call is going to error. I don't think that call would error if the namespace would have no ConfigMaps so the only error then would be a problem with k8s which would grind everything to a halt anyways.

But if a namespace can fail independently then it would make sense to be able to just have a warning for it. I think we can let it be like this for now and if it becomes a problem we can add something like `--skip-errors` flag.

2022-01-24 10:23 UTC, joelhoisko commented on cmd/tools/automate/update-dolittle-config.go
> +		// TODO this might be to strict, perhaps we have a flag to let them skip?
This is in the `processOne()` function, and if the function can't get the configmap that it should process it makes sense that the function errors as it can't continue to the next step, which would be to update the not-found configmap meaning the function breaks.

The function could return return a `(err error, ok bool)` which we could check that did it do it's job correctly though. Then we could have the same kind of `--skip-errors` flag from my other comment.

2022-01-24 10:38 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +		// TODO this is a sign it might not be using a runtime, maybe we skip
I started to think first that I don't think it's the `UpdateConfigMap()` functions job to check and make assumptions about what kind of configmap it's supposed to update. But then I realised that this function doesn't actually just update configmaps as a generic thing, but rather only adds the specific `platform.json` part into it. In that case either this function (which could maybe be called `AddMicroserviceConfigmapPlatformData()` or something equally ugly and verbose) or it's caller should make sure that the given configmap is a dolittle configmap.

Currently I don't think adding some new data to the dolittle configmaps (even the ones that don't use the Runtime) would create any problems except it would add noise to the configmaps. But you could make the same argument for adding the `platform.json` data into microservices that aren't going to use it...

And as you said, we don't really use the `microservice-kind` annotation in a defined way currently so I don't think you can draw too many conclusions from it.

So in the end I'm fine if we error there or write a warning and skip the update.

2022-01-24 10:44 UTC, joelhoisko commented
One thing that I also learned just now is that in platform-api when writing fields for the logger we use both `microservice_id` and `microserviceID` fields. Which one should be our standard? From a JSON perspective I like the camelCased version more as it feels more JSONy (you wouldn't write JS objects with snake_cased properties).

2022-01-24 10:58 UTC, joelhoisko commented on cmd/tools/automate/update-dolittle-config.go
> +					// TODO this might be to strict, perhaps we have a flag to let them skip?
Or maybe `--ignore-errors` sounds more professional

2022-01-24 11:58 UTC, freshteapot commented on pkg/platform/automate/share.go
> +		// TODO wwhen we explicitly set the kind as an annotation we can rely on it
If we dont have ["dolittle.io/microservice-kind"] default to unknown.

2022-01-25 07:42 UTC, freshteapot commented
> One thing that I also learned just now is that in platform-api when writing fields for the logger we use both `microservice_id` and `microserviceID` fields. Which one should be our standard? From a JSON perspective I like the camelCased version more as it feels more JSONy (you wouldn't write JS objects with snake_cased properties).

I created a ticket to reflect your concerns, I am not sold on the "js object" reason :).
I do not hold a strong opinion on either way.

You are very welcome to pull the task into the iteration and make the changes you want, after this PR lands?

https://app.asana.com/0/1201325052247030/1201713848182574/f

2022-01-25 07:45 UTC, freshteapot commented on pkg/platform/automate/share.go
> +		// TODO this is a sign it might not be using a runtime, maybe we skip
We should rename this function to make it clearer what it is doing.

microservice-kind, is going to be added https://app.asana.com/0/1201325052247030/1201451644838466/f.

2022-01-25 07:47 UTC, freshteapot commented on cmd/tools/automate/update-dolittle-config.go
> +		// TODO this might be to strict, perhaps we have a flag to let them skip?
I think we should wait before skipping errors logic.
We might only run the script once.

Just making the script has led to progress on how to make the next script easier :).

2022-01-25 07:49 UTC, freshteapot commented on cmd/tools/automate/update-dolittle-config.go
> +					// TODO this might be to strict, perhaps we have a flag to let them skip?
We should find out :).
I think if the error is not found we should move on.
If the error is anything but, it should fail.

Let us start by taking the errors seriously :).

2022-01-25 16:47 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +		// TODO wwhen we explicitly set the kind as an annotation we can rely on it
I'm defaulting to the new `MicroserviceKindUnknown` in this function now if the kind isn't specified in the resource. It's a step at least.

2022-01-25 16:48 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +		// TODO this is a sign it might not be using a runtime, maybe we skip
I've renamed it to `AddDataToConfigMap()`

2022-01-26 08:59 UTC, joelhoisko commented
Copying the todo from the top level summary here before I forget:

# Todo
- [x] We should also discuss if the managedFields should be removed from the output.
- [ ] ~~Test in local cluster~~ (not feasible with the deployments as I can't just write a script to import the ones from the cluster)
- [x] Hook up platform.json to volume
- [x] ConvertObjectMetaToMicroservice check for microservice-kind, default to unknown

2022-01-26 09:49 UTC, joelhoisko commented
# Dry run test

1. Change your context to the prod cluster
2. Run this command to only print out the changed configmap and then the deployment (it's dry run):
```sh
go run main.go tools automate add-platform-config \
        --application-id="11b6cf47-5d9f-438f-8116-0d9828654657" \
        --environment="Dev" \
        --microservice-id="ec6a1a81-ed83-bb42-b82b-5e8bedc3cbc6" \
        --dry-run=true | jq -r '.data'
```
3. Look at the data in the terminal and see that the `platform.json` volumeMount is added to the runtime container in the deployment and that the configmap also has a `platform.json` key added to it.

2022-01-26 13:55 UTC, freshteapot requested changes
We are getting there :)

2022-01-26 13:55 UTC, freshteapot commented on cmd/tools/automate/pull-microservice-deployment.go
> +			// var runtimeDeployments []appsv1.Deployment
Please remove the comments here.

2022-01-26 13:55 UTC, freshteapot commented on cmd/tools/automate/pull-dolittle-config.go
> +			err = writeConfigMapsToDirectory(args[0], configMaps, scheme, serializer)
What is the downside of moving writeConfigMapsToDirectory into pkg/automate as WriteConfigMapsToDirectory?

2022-01-26 13:55 UTC, freshteapot commented on cmd/tools/automate/pull-microservice-deployment.go
> +			err = writeDeploymentsToDirectory(args[0], deployments, scheme, serializer)
What is the downside of moving writeDeploymentsToDirectory into pkg/automate as WriteDeploymentsToDirectory?

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/command_input.go
> +func ParseMicroserviceMetadata(input string) (platform.MicroserviceMetadataShortInfo, error) {
Better name :)

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +	err = appsv1.AddToScheme(scheme)
This no longer reflects the func signature.
Is there a downside to adding many schemes?
If not maybe we rename the  the func.

Otherwise we might need to copy and paste for each resource.

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +func GetRuntimeDeployment(ctx context.Context, client kubernetes.Interface, applicationID string, environment string, microserviceID string) (int, appsv1.Deployment, error) {
I think we should refactor this function out.
We have K8sGetDeployment
```go
deployment, err := microserviceK8s.K8sGetDeployment(r.k8sClient, ctx, namespace, microserviceID)
```

Let us move the func here.
We can add a note to come back to this file after we land applications. To tidy up some of the structure.

I would like to reorder the context and client in K8sGetDeployment.
Then use this function to lookup the microservice.
Then a helper a function that takes a deployment and returns the "index, container".

```go
func GetContainerIndex(deployment appsv1.Deployment, name string) int {
	for index, container := range deployment.Spec.Template.Spec.Containers {
		if container.Name == name {
			return index
		}
	}
	return -1
}
```

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +func GetNamespaces(ctx context.Context, client kubernetes.Interface) []corev1.Namespace {
Can we replace the use of getNamespaces in tools/studio to use this and then delete the function.

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +func IsApplicationNamespace(namespace corev1.Namespace) bool {
Can we replace the use of isApplicationNamespace in tools/studio to use this and delete the function.

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +	_, err := client.AppsV1().Deployments(deployment.Namespace).Update(ctx, &deployment, metav1.UpdateOptions{})
Love it!

2022-01-26 13:55 UTC, freshteapot commented on pkg/platform/automate/share.go
> +
The use of else is not needed here. I guess it might be a style thing, but we have a default "unknown" and we plan on changing it "if" something is different.

We also have very similar logic in https://github.com/dolittle/platform-api/blob/c978b7ba019986fe33a3077064facb14dc6c1e31/pkg/platform/k8s_repo.go#L199-L202

Which makes me believe we should hoist this into a func, and then clean up the code in both places.
To start with, I think the signature could be "annotations". and return kind, if its finds it, or unknown.


```suggestion
	kind := platform.MicroserviceKindUnknown
	if kindString, ok := annotations["dolittle.io/microservice-kind"]; ok {
		kind = platform.MicroserviceKind(kindString)
	}```

2022-01-26 14:23 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +func GetRuntimeDeployment(ctx context.Context, client kubernetes.Interface, applicationID string, environment string, microserviceID string) (int, appsv1.Deployment, error) {
Note for myself: move things to automate

2022-01-27 09:51 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +	err = appsv1.AddToScheme(scheme)
I just changed the function name to `InitializeSchemeAndSerializer()`. I don't know if there's any downside to adding many schemes, but I assume it's negligible. Digging behind the scenes the `AddToScheme()` call essentially just adds some more stuff to the schemes `gvkToType map[schema.GroupVersionKind]reflect.Type` and `typeToGVK map[reflect.Type][]schema.GroupVersionKind` properties. And it just adds tens of elements so I think we're all fine here.

2022-01-27 10:15 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +func GetRuntimeDeployment(ctx context.Context, client kubernetes.Interface, applicationID string, environment string, microserviceID string) (int, appsv1.Deployment, error) {
- I removed the `K8sGetDeployment()` function
- I added `GetDeployment()` to automate that takes a namespace and microserviceID, getting rid of the applicationID and environment
- I added a `GetContainerIndex()` function to automate
- I removed the `GetRuntimeDeployment()` function
- Fixed all the places that used the removed functions to use the new ones

2022-01-27 10:31 UTC, joelhoisko commented on pkg/platform/automate/share.go
> +
Yeah I was debating myself that should I be setting the variable first by default to unknown or using an if/else.

I created function `GetMicroserviceKindFromAnnotations` in the platform package. I couldn't make it inside `automate` as we'd get a cyclical import (`automate` imported the `platform.MicroserviceKind` type, `platform` imported `automate` to get the kind -> cyclical import).

2022-01-27 10:42 UTC, joelhoisko commented on cmd/tools/automate/pull-dolittle-config.go
> +			err = writeConfigMapsToDirectory(args[0], configMaps, scheme, serializer)
I was thinking that the pkg/automate was for generic stuff that can be shared, but I guess the `WriteConfigMapsToDirectory()` function could also be used by other pieces of code someday. I moved it and removed the `scheme` and `serializer` from the args as it doesn't make sense to have to pass it in there anymore.

2022-01-27 10:43 UTC, joelhoisko commented on cmd/tools/automate/pull-microservice-deployment.go
> +			err = writeDeploymentsToDirectory(args[0], deployments, scheme, serializer)
I moved it, see my comment about `WriteConfigMapsToDirectory()`

2022-01-27 13:09 UTC, freshteapot commented on pkg/platform/automate/share.go
> +		// TODO this is a sign it might not be using a runtime, maybe we skip
Nice :) I am excited by this func.

2022-01-27 13:16 UTC, freshteapot commented on cmd/tools/automate/pull-dolittle-config.go
> +			err = writeConfigMapsToDirectory(args[0], configMaps, scheme, serializer)
okay :).

2022-01-27 13:17 UTC, freshteapot commented on cmd/tools/automate/pull-microservice-deployment.go
> +			err = writeDeploymentsToDirectory(args[0], deployments, scheme, serializer)
Noted, we will make the pkg structure better in due course.

2022-01-27 13:17 UTC, freshteapot commented on pkg/platform/automate/share.go
> +	err = appsv1.AddToScheme(scheme)
Game on :D.

2022-01-27 13:18 UTC, freshteapot commented on pkg/platform/automate/share.go
> +func GetRuntimeDeployment(ctx context.Context, client kubernetes.Interface, applicationID string, environment string, microserviceID string) (int, appsv1.Deployment, error) {
<3

2022-01-27 13:21 UTC, freshteapot approved these changes
Some nice features landing via this PR:

- Now we know how to dump beautiful yaml files (configmaps + deployments)
- Reading in ndjson to do things
- Able to update configmaps easier now (thinking of new tenants)
- We have a little recipe on how to update "things in the cluster".

Happy days

As I mentioned in teams.
I think when it comes to deploying this, we can hit all none production now.
Then we need to think a little how to handle production, as the update does trigger a restrart on the pods.

2022-01-27 13:40 UTC, merged