Refactor CLI commands
dolittle/platform-api pull request #90
Opened 2022-02-22 12:34 UTC by joelhoisko

## Summary

Changed the CLI commands:
- New root command `platform tools helpers` that includes 3 different subcommands. The `helpers` signifies that these commands are meant for us internally to make manual steps easier. They don't write to the platform, only output helper stuff to stdout for us:
  - `terraform` for creating prefilled HCL files. Replaces the old `platform tools terraform` commands.
  - `kubernetes` for creating prefilled K8s YAML files. Replaces the `platform tools jobs` YAML creation commands.
  - `commands` for creating commands to copy-paste into your own terminal. Replaces the `platform tools studio delete-*` commands.
- Renamed `microservice` command and package to `api`
- Added new commands to `explore` to consolidate our "exploratory" commands. These are commands which are meant for us to manually have a look at them or to pipe them to other commands:
  - `studio-customers` to get the `customer.json`. Replaces `platform tools studio get-customer`
  - `job-status` to get a K8s Job pods status. Replaces `platform tools jobs status`
  - `microservices` to get all microservices metadata. Replaces `platform tools automate get-microservice-metadata`

[Miro board for brainstorming](https://miro.com/app/board/uXjVOKmmIm4=/)

2022-02-22 12:41 UTC, joelhoisko commented
The `helpers` command could also be renamed to `templates` to try to hammer down the idea that these commands only output stuff into stdout for you to copy paste. Or maybe there's a better name, as `templates` sounds like it deals with... templates which these things kinda are but kinda aren't.

2022-02-22 14:41 UTC, freshteapot requested changes
Nice start @joelhoisko.
The helper functions that create jobs, need fixing in other parts of the code, as currently it is breaking.

- https://github.com/dolittle/platform-api/blob/main/pkg/platform/job/k8s/application.go#L15
- https://github.com/dolittle/platform-api/blob/main/pkg/platform/job/k8s/customer.go#L17

I am happy to adapt to using explore and helpers, I will have to consult you going forward to try and learn when to put them under "helpers" and "explore" vs other parts.

I see in the asana task there are sub-tasks around updating the k8s file etc, this will need to happen for the server.
Also, it is not documented very well (landed via #59) but you will also need to update the operations image environment variable as well as the deployment image.

Once we are closer to deploying, I am happy to watch you try and acknowledge all the missing documentation and improve it.

2022-02-22 14:41 UTC, freshteapot commented on cmd/tools/helpers/kubernetes/application-job.go
> +var applicationJobCMD = &cobra.Command{
Why do you consider these helpers?

I struggled with this sub-package, as "jobs" has a meaning in kubernetes.
For me, I used to love "helpers" and "utils", but then I took heart when I was reading in golang about avoid using "utils" for it doesnt provide context. I came to realise "helpers" also dont provide context.

https://github.com/golang/go/wiki/CodeReviewComments#package-names

Changing this and the customer one, also means you need to dig into the code and change files within https://github.com/dolittle/platform-api/tree/main/pkg/platform/job/k8s which call these functions.

2022-02-22 14:41 UTC, freshteapot commented on cmd/tools/helpers/root.go
> +Helpers to create commands and HCL/YAML files to copy-paste. These commands are meant to make our life easier by creating copy-paste ready commands.
With the large PR #59 these commands are actually used by the system (https://github.com/dolittle/platform-api/tree/main/pkg/platform/job/k8s). I raise this point, as these commands are not just for the "platform-engineer".

Should we re-work the description to make that clear?
With the above knowledge, does "helpers" make sense?

2022-02-23 09:36 UTC, joelhoisko commented on cmd/tools/explore/studio-customers.go
> +var studioCustomersCMD = &cobra.Command{
> My initial thinking around "explore" would be throw away commands to explore, maybe whilst developing or before we find value in them.

Okay I see then my confusion. When looking at the commands I only saw that they were just getting data in a structured way for us to explore or potentially to use in other commands and that they were read-only commands without side effects on the platform. So then it made sense to group these different "getters" of data into a single point and if you'd want to make another command that gets/exports data from the platform it would make sense for it to live there. So I didn't get that their point was to be "exploratory", just that they were a means for us to explore the data and to pipe it to other tools.

 > If I was new to the code base, I would think to find studio customers unders studio, not explore.

I agree, I also wasn't 100% sure on whether the `customers.json` getter command should live. I wanted to have it with the other "gettery" and read-only commands in `explore`, but it has more context while living in the `studio` command. Maybe it would then make sense to structure the `studio` subcommands like this:
- `studio`
  - `update` as all of these commands are about updating the existing `*.json` files.
    - `terraform`
    - `studio`
    - `application`
  - `create`
    - `service-account`
  - `get`
    - `customers`

This way we'd have different verbs on to act on the different subjects of Studio. The `studio admin` command could also be refactored into this structure over time. What do you think?

2022-02-23 09:42 UTC, freshteapot commented on cmd/tools/explore/studio-customers.go
> +var studioCustomersCMD = &cobra.Command{
Let us do some brainstorming :).
See if it helps with the nice subcommands above, or if it confuses the matter.

Thinking about the jobs as they speak "application" and / or "customer" and less "technology".

2022-02-23 10:12 UTC, joelhoisko commented on cmd/tools/helpers/kubernetes/application-job.go
> +var applicationJobCMD = &cobra.Command{
I agree, I also don't like `helpers` or `utils` etc package names and I try to avoid them. Which is why I was also maybe thinking of calling this `templates` instead. I'm not sure that is there a nice word for what these commands do. Maybe `cli-templates`? The reason why I moved them into their own sub package was that I saw an opportunity to consolidate similar commands into one place. And I didn't like these helper commands names (they sounded like they were actually creating a customer or application), but thinking about it now maybe we should aim for more of the contextual "subject of the platform" first approach and then group things inside that subject.

So kinda like what I talked about the `studio` command, we could do something like:
- `job`
  -  `status` (so move the thing back from `explore`). We could also have the whole `job get status` thing going on, but I'm not sure that are there other things to "get" from a job than it's status.
  - `create` and in the future we could also use this to actually create jobs instead of just templates for the jobs
    - `customer-template`
    - `application-template`
  - OR
  - `template` as in the verb or we could be crazy and use ["templatize"](https://english.stackexchange.com/a/520300)
  	- `customer`
  	- `application`

The one downside I see with going with the `platform tools <subject> <verbs>` approach is that we're going to have a lot more subjects than verbs. For example in this approach the `explore` command isn't that different from "helpers" or "utils". Instead we'd want to have `platform tools ingress <get/list/something>`. And sometimes it's not that easy to figure out what the subject would be. What is the subject `import-dolittle-configmaps` is changing? I guess `kubernetes` or `platform` or maybe `configmaps`. And `pull-dolittle-config`'s subject is ultimately the Operations repo so maybe it could live in `platform tools <operations/repo> update dolittle-config`. And maybe the hardest one would be the `delete-application` and `delete-customer` commands as they ultimately are templates for the platform. So maybe `platform template delete application`? Or `platform tools platform template delete application`? But maybe at that point we could also get rid of the `tools` subcommand too...

I feel like that after having writing all of this I got some new ideas along the lines of `platform <subject> <verb>`ifying the CLI a bit more. But to get back to the task at hand, I propose this command structure (I'm also okay with `templatize`):
- `platform tools job status`
- `platform tools job template customer/application`
- `platform tools terraform template application`
- `platform tools terraform template customer`
- `platform template delete application`
- `platform template delete customer`
- Get rid of `helpers`

And also I didn't know that the job template commands were used in the jobs, I can fix that too when we land on the commands names.

2022-02-23 14:06 UTC, joelhoisko commented on cmd/tools/helpers/kubernetes/application-job.go
> +var applicationJobCMD = &cobra.Command{
Implemented my proposal with the `template` verb.

2022-02-23 14:06 UTC, joelhoisko commented on cmd/tools/explore/studio-customers.go
> +var studioCustomersCMD = &cobra.Command{
Implemented the changes to `studio`.

2022-02-23 14:20 UTC, joelhoisko commented on cmd/tools/helpers/root.go
> +Helpers to create commands and HCL/YAML files to copy-paste. These commands are meant to make our life easier by creating copy-paste ready commands.
I fixed the created jobs to use the new command structure.

2022-02-24 20:08 UTC, freshteapot requested changes
Its looking good @joelhoisko.
I have spotted a few minor issues, bu the one main issue to clarify is 

```sh
/app/bin/app tools terraform template customer
```

Is not currently defined

```sh
go run main.go tools terraform template
Create pre-filled Terraform HCL

Usage:
  platform tools terraform template [command]

Available Commands:
  application         Write terraform output for a customer application
  create-customer-hcl Write terraform output for a customer

Flags:
  -h, --help   help for template

Global Flags:
      --platform-environment string   Platform environment (dev or prod), not linked to application environment (default "dev")

Use "platform tools terraform template [command] --help" for more information about a command.
```

I am also reminded, I haven't shared the secret for the service principle nor documented how to run this locally. (maybe you got it from the cluster :)).

2022-02-24 20:08 UTC, freshteapot commented on cmd/tools/job/template/customer.go
> +	Outputs a k8s job to create a customers application
```suggestion
	Outputs a k8s job to create a customer
```

2022-02-24 20:08 UTC, freshteapot commented on cmd/tools/studio/get/customers.go
> +	go run main.go tools explore studio-customers
```suggestion
	go run main.go tools studio get customers
```

2022-02-24 20:08 UTC, freshteapot commented on cmd/tools/studio/update/application.go
> +	Short: "Update the application.json",
Not sure if it matters, but it also creates, not just updates.

2022-02-24 20:08 UTC, freshteapot commented on cmd/tools/terraform/template/customer.go
>  	Use:   "create-customer-hcl",
Does this need changing to match application?

2022-02-24 20:08 UTC, freshteapot commented on cmd/tools/terraform/template/customer.go
> +	go run main.go tools terraform template customer --name="Test Marka" --platform-environment="dev"
The "use" doesnt match.

2022-02-24 20:08 UTC, freshteapot commented on pkg/platform/job/k8s/application.go
>  						gitUpdateStudioTerraformInfo(platformImage, platformEnvironment, customerID, branch),
Do you want to change the name of this to be inline with the change above?

2022-02-24 20:08 UTC, freshteapot commented on pkg/platform/job/k8s/customer.go
> +/app/bin/app tools terraform template customer \
This should have failed, based on the comment further up, or I am blind :).

2022-02-25 08:35 UTC, joelhoisko commented on cmd/tools/terraform/template/customer.go
> +	go run main.go tools terraform template customer --name="Test Marka" --platform-environment="dev"
I fixed the command to be `tools terraform template customer`

2022-02-25 09:00 UTC, joelhoisko commented on cmd/tools/studio/update/application.go
> +	Short: "Update the application.json",
True, I guess it should be seen as an upsert, as should `platform tools studio update terraform` as well. And the `platform tools studio update studio` command is actually an "resetsert" or maybe just a reset then (I guess it's okay that a "reset" also creates)?

So we could have:
- `studio`
	- `upsert`
		- `terraform`
		- `application`
	- `reset`
		- `studio`

It makes sense, I just feel bad for dealing with this 3 days after tech debt day. I'll fix them.

2022-02-25 09:17 UTC, joelhoisko commented on cmd/tools/studio/update/application.go
> +	Short: "Update the application.json",
Actually I'm not 100% sure if `reset studio` is the correct term. Reading the code it's point seems to be to create default studio configs and/or reset existing ones to default. But you can also configure the command with flags to update/create a non-default studio config so it doesn't really work as "reset", even though that kinda was it's original idea.

So maybe it should live in `upsert`. I'll fix it.

2022-02-25 09:33 UTC, joelhoisko commented on cmd/tools/studio/update/application.go
> +	Short: "Update the application.json",
I fixed them all to be `upsert` and also fixed the jobs and their methods name to use the word "Upsert" instead of "Update".

2022-02-25 09:35 UTC, joelhoisko commented on cmd/tools/terraform/template/customer.go
>  	Use:   "create-customer-hcl",
I assume you're talking about when I forgot to rename the `Use:` command to `customer`? Or what do you mean "match application"? The application command variable is called `applicationCMD` so it makes sense that the customer command variable is called `customerCMD`.

2022-02-25 09:40 UTC, joelhoisko commented on pkg/platform/job/k8s/application.go
>  						gitUpdateStudioTerraformInfo(platformImage, platformEnvironment, customerID, branch),
I'm not sure which of the methods you're talking about. I've already renamed the `toolsStudioUpdateTerraform()` to `toolsStudioUpsertTerraform()`. For the `gitUpdateStudioTerraformInfo()` method I don't think I care enough to go renaming everything right now.

2022-02-25 09:40 UTC, joelhoisko commented on pkg/platform/job/k8s/customer.go
> +/app/bin/app tools terraform template customer \
You weren't blind. Fixed.

2022-02-25 10:22 UTC, freshteapot approved these changes
🚢 🇮🇹 
Confirmed in dev :), made a customer and an application.

2022-02-25 10:28 UTC, merged