Add a http handler for getting a customers studio.json
dolittle/platform-api pull request #95
Opened 2022-03-02 16:01 UTC by joelhoisko

## Summary

Adds new endpoints:
- GET `/studio/customer/{customerID}` for fetching a single customer's `studio.json` file. The configuration in the response is camelCased so that it's nicer to consume in JavaScript/TypeScript.
- POST `/studio/customer/{customerID}` for updating a single customer's `studio.json` file. The request should be camelCased.

Example request payload for disabling all environments:
```json
{"buildOverwrite":true,"disabledEnvironments":["*"],"canCreateApplication":true}
```

Curl example:
```sh
echo -n '{"buildOverwrite":true,"disabledEnvironments":[],"canCreateApplication":true}' \ 
| curl -X POST localhost:8081/studio/customer/CUSTOMER_ID \
 -H "x-shared-secret: FAKE" \
 -H "user-id: DEVELOPMENT_USER_ID" \
 -H "tenant-id: DEVELOPMENT_CUSTOMER_ID" \
 -H "Content-Type: application/json" \
 --data-binary @-
```

These endpoints enable us to modify the `studio.json`, so that we can enable or disable the creation of microservices per customer more easily.

## Reference
- [Related Studio PR](https://github.com/dolittle/Studio/pull/159)
- [Asana](https://app.asana.com/0/1201885260673030/1201894099742054)

2022-03-04 08:44 UTC, freshteapot requested changes
Nice work @joelhoisko, will follow up after my next 2 meetings.

- What to do about hasAccess
- can you run "go mod tidy", when I run it, it is different
- Love the tests, nice to see the coverage rise

I haven't tested it yet with the frontend, just read the code.

2022-03-04 08:44 UTC, freshteapot commented on pkg/platform/studio/service.go
> +	studioConfig, err := s.storageRepo.GetStudioConfig(customerID)
Over in the customer section, we use "hasAcess".
Do you think we should use has access here to reduce access?

2022-03-04 08:44 UTC, freshteapot commented on pkg/platform/studio/service.go
> +	err := s.storageRepo.SaveStudioConfig(customerID, studioConfig)
Over in the customer section, we use "hasAcess".
Do you think we should use has access here to reduce access as it is a write operation?

2022-03-04 08:44 UTC, freshteapot commented on pkg/platform/studio/service_test.go
> +			request, _ := http.NewRequest("GET", customerUrl, nil)
I cant give very detailed reasons, but it seems "better" to use httptest here, what do you think?
Or why are you using http.NewRequest?

ie

```go
req = httptest.NewRequest("GET", url, nil)
```
there are examples in the tests which do this.

2022-03-04 08:44 UTC, freshteapot commented on pkg/platform/studio/service_test.go
> +			router.ServeHTTP(recorder, request)
I like what you have done here, what I did elsewhere is a little more clunky.

2022-03-07 09:27 UTC, joelhoisko commented on pkg/platform/studio/service_test.go
> +			request, _ := http.NewRequest("GET", customerUrl, nil)
I changed to use the `httptest.NewRequest()`, also found [this SO comment about it's intended use](https://stackoverflow.com/a/45682537/5806412).

2022-03-07 09:29 UTC, joelhoisko commented on pkg/platform/studio/service.go
> +	err := s.storageRepo.SaveStudioConfig(customerID, studioConfig)
Good point, I'll update the tests and add a check for it

2022-03-07 14:59 UTC, joelhoisko commented on pkg/platform/studio/service.go
> +	err := s.storageRepo.SaveStudioConfig(customerID, studioConfig)
I moved the `hasAccess()` method from the `customer` package to `k8s.Repo` package's `RepoRoleBinding` interfaces `HasUserAdminAccess(userID string) (bool, error)` method as it felt the closest place to put it without creating a whole new interface and struct for it in side `customer` package. But I also get if the `k8s.Repo` package is supposed to only deal in k8s resources instead of our own domain.

I fixed it to work with the customer service and with the studio and tested the studio parts locally (with the `PLATFORM_ENVIRONMENT="dev"` env variable on platform-api).

2022-03-10 14:21 UTC, freshteapot requested changes
@joelhoisko 1 minor change and then its good :).

I can't quite decide if we need "studio" as its own api endpoint, but happy to find out.
I have been flip flopping between the url you have created and something

> /customer/{customerID}/studoconfig

> /customer/{customerID}/config

And then having an attribute for studio.

I don't think it really matters as we try and figure it out :).

2022-03-10 14:21 UTC, freshteapot commented on pkg/platform/studio/service.go
> +		"method":      "Get",
Being the save func, I think we want save :)

```suggestion
		"method":      "Save",
```

2022-03-15 09:31 UTC, merged